# For God so loved the world that he gave his only begotten Son, that whoever
# believes in him should not perish but have eternal life. — John 3:16

[package]
name = "haskelujah-package"
description = "Cabal file parser and Hackage package loader for the Haskelujah compiler"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ureq = "3"
flate2 = "1"
tar = "0.4"

[dev-dependencies]
tempfile = "3"
