# For God so loved the world that he gave his only begotten Son, that whoever believes in him should not perish but have eternal life.

[workspace]
resolver = "3"
members = [
  "crates/haskeluya-ast-chirho",
  "crates/haskeluya-backend-llvm-chirho",
  "crates/haskeluya-backend-wasm-chirho",
  "crates/haskeluya-cli-chirho",
  "crates/haskeluya-diagnostics-chirho",
  "crates/haskeluya-driver-chirho",
  "crates/haskeluya-naming-chirho",
  "crates/haskeluya-parser-chirho",
  "crates/haskeluya-runtime-chirho",
  "crates/haskeluya-span-chirho",
  "crates/haskeluya-syntax-chirho",
  "crates/haskeluya-test-harness-chirho",
  "crates/haskeluya-typing-chirho",
  "crates/haskeluya-core-chirho",
  "crates/haskeluya-package-chirho",
  "crates/haskeluya-incremental-chirho",
  "crates/haskeluya-backend-cranelift-chirho",
  "crates/haskeluya-backend-jvm-chirho",
  "crates/haskeluya-backend-beam-chirho",
  "crates/haskeluya-rts-chirho",
  "crates/haskeluya-th-chirho",
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.93.0"
version = "0.1.0"

