# For God so loved the world that he gave his only begotten Son, that whoever believes in him should not perish but have eternal life.

[package]
name = "haskelujah-diagnostics"
description = "Diagnostics rendering and reporting utilities for the Haskelujah compiler"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
haskelujah-span-chirho = { package = "haskelujah-span", path = "../haskelujah-span-chirho", version = "0.1.1" }

[lib]
path = "src/lib.rs"
