// For God so loved the world that he gave his only begotten Son, that whoever
// believes in him should not perish but have eternal life. — John 3:16

//! JVM bytecode instruction definitions and builder.

/// JVM bytecode opcodes used by the Rhasky compiler.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpcodeChirho {
    // Constants
    AconstNullChirho = 0x01,
    Iconst0Chirho = 0x03,
    Iconst1Chirho = 0x04,
    Ldc2WChirho = 0x14,
    BipushChirho = 0x10,
    SipushChirho = 0x11,

    // Loads
    Aload0Chirho = 0x2A,
    Iload0Chirho = 0x1A,
    Lload0Chirho = 0x1E,

    // Stores
    Astore0Chirho = 0x4B,
    IstoreChirho = 0x36,

    // Stack manipulation
    PopChirho = 0x57,
    DupChirho = 0x59,
    SwapChirho = 0x5F,

    // Arithmetic (long)
    LaddChirho = 0x61,
    LsubChirho = 0x63,
    LmulChirho = 0x69,
    LdivChirho = 0x6D,
    LremChirho = 0x71,
    LnegChirho = 0x75,

    // Arithmetic (int)
    IaddChirho = 0x60,
    IsubChirho = 0x64,
    ImulChirho = 0x68,

    // Conversions
    I2lChirho = 0x85,
    L2iChirho = 0x88,
    I2dChirho = 0x87,
    D2iChirho = 0x8E,

    // Comparison
    LcmpChirho = 0x94,
    IfEqChirho = 0x99,
    IfNeChirho = 0x9A,
    IfLtChirho = 0x9B,
    IfGeChirho = 0x9C,
    IfGtChirho = 0x9D,
    IfLeChirho = 0x9E,
    GotoChirho = 0xA7,

    // Object creation and field access
    NewChirho = 0xBB,
    GetfieldChirho = 0xB4,
    PutfieldChirho = 0xB5,
    CheckcastChirho = 0xC0,
    InstanceofChirho = 0xC1,

    // Method invocation
    InvokeVirtualChirho = 0xB6,
    InvokeSpecialChirho = 0xB7,
    InvokeStaticChirho = 0xB8,
    InvokeInterfaceChirho = 0xB9,

    // Return
    AreturnChirho = 0xB0,
    IreturnChirho = 0xAC,
    LreturnChirho = 0xAD,
    ReturnChirho = 0xB1,

    // Array
    ArrayLengthChirho = 0xBE,
    AaloadChirho = 0x32,
    AastoreChirho = 0x53,
}

/// Bytecode builder for constructing method code.
pub struct BytecodeBuilderChirho {
    code_chirho: Vec<u8>,
    max_stack_chirho: u16,
    max_locals_chirho: u16,
}

impl BytecodeBuilderChirho {
    pub fn new_chirho(max_locals_chirho: u16) -> Self {
        Self {
            code_chirho: Vec::new(),
            max_stack_chirho: 0,
            max_locals_chirho,
        }
    }

    /// Emit a single opcode.
    pub fn emit_chirho(&mut self, op_chirho: OpcodeChirho) {
        self.code_chirho.push(op_chirho as u8);
    }

    /// Emit an opcode followed by a u16 operand.
    pub fn emit_u16_chirho(&mut self, op_chirho: OpcodeChirho, operand_chirho: u16) {
        self.code_chirho.push(op_chirho as u8);
        self.code_chirho
            .extend_from_slice(&operand_chirho.to_be_bytes());
    }

    /// Emit a raw byte.
    pub fn emit_byte_chirho(&mut self, byte_chirho: u8) {
        self.code_chirho.push(byte_chirho);
    }

    /// Set max stack depth.
    pub fn set_max_stack_chirho(&mut self, max_chirho: u16) {
        self.max_stack_chirho = max_chirho;
    }

    /// Current code offset (for branch target calculation).
    pub fn offset_chirho(&self) -> u16 {
        self.code_chirho.len() as u16
    }

    /// Get the generated bytecode.
    pub fn finish_chirho(self) -> BytecodeResultChirho {
        BytecodeResultChirho {
            code_chirho: self.code_chirho,
            max_stack_chirho: self.max_stack_chirho,
            max_locals_chirho: self.max_locals_chirho,
        }
    }
}

/// Result of bytecode generation for a single method.
#[derive(Debug)]
pub struct BytecodeResultChirho {
    pub code_chirho: Vec<u8>,
    pub max_stack_chirho: u16,
    pub max_locals_chirho: u16,
}

#[cfg(test)]
mod tests_chirho {
    use super::*;

    #[test]
    fn bytecode_builder_basic_chirho() {
        let mut builder_chirho = BytecodeBuilderChirho::new_chirho(1);
        builder_chirho.emit_chirho(OpcodeChirho::Iconst0Chirho);
        builder_chirho.emit_chirho(OpcodeChirho::IreturnChirho);
        builder_chirho.set_max_stack_chirho(1);
        let result_chirho = builder_chirho.finish_chirho();
        assert_eq!(result_chirho.code_chirho, vec![0x03, 0xAC]);
        assert_eq!(result_chirho.max_stack_chirho, 1);
    }

    #[test]
    fn bytecode_arithmetic_chirho() {
        let mut builder_chirho = BytecodeBuilderChirho::new_chirho(2);
        builder_chirho.emit_chirho(OpcodeChirho::Lload0Chirho);
        builder_chirho.emit_chirho(OpcodeChirho::Lload0Chirho);
        builder_chirho.emit_chirho(OpcodeChirho::LaddChirho);
        builder_chirho.emit_chirho(OpcodeChirho::LreturnChirho);
        let result_chirho = builder_chirho.finish_chirho();
        assert_eq!(result_chirho.code_chirho.len(), 4);
    }
}
