# For God so loved the world that he gave his only begotten Son, that whoever believes in him should not perish but have eternal life.

[package]
name = "haskelujah-runtime"
description = "STG evaluator and runtime services for the Haskelujah compiler"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
haskelujah-rts-chirho = { package = "haskelujah-rts", path = "../haskelujah-rts-chirho", version = "0.1.0" }
