// For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life. — John 3:16 (KJV)

//! Resolve Core primitives explicitly. An unsupported operation is an error when
//! demanded, never an invented arithmetic operation.
//! Workflow: testing-chirho/execution-oracles-chirho.md.

use super::{ArgSourceChirho, CodeChirho, LowerCtxChirho, PrimOpKindChirho, ValueChirho};

#[cfg(test)]
mod tests_chirho;

impl LowerCtxChirho {
    pub(super) fn emit_named_primitive_chirho(
        &mut self,
        name_chirho: &str,
        arguments_chirho: Vec<ArgSourceChirho>,
    ) -> u32 {
        let instruction_chirho = match primop_name_to_kind_chirho(name_chirho) {
            Some(operation_chirho) => CodeChirho::PrimChirho {
                op_chirho: operation_chirho,
                args_chirho: arguments_chirho,
            },
            None => CodeChirho::PrimChirho {
                op_chirho: PrimOpKindChirho::ErrorChirho,
                args_chirho: vec![ArgSourceChirho::StaticChirho(ValueChirho::StringChirho(
                    format!("unsupported STG primitive: {name_chirho}"),
                ))],
            },
        };
        self.emit_chirho(instruction_chirho)
    }
}

/// Map a primop name from Core to a `PrimOpKindChirho`.
fn primop_name_to_kind_chirho(name_chirho: &str) -> Option<PrimOpKindChirho> {
    Some(match name_chirho {
        "isHeapObjectChirho#" => PrimOpKindChirho::IsHeapObjectChirho,
        "+#" => PrimOpKindChirho::AddIntChirho,
        "-#" => PrimOpKindChirho::SubIntChirho,
        "*#" => PrimOpKindChirho::MulIntChirho,
        "div#" => PrimOpKindChirho::DivIntChirho,
        "mod#" => PrimOpKindChirho::ModIntChirho,
        "quot#" => PrimOpKindChirho::QuotIntChirho,
        "rem#" => PrimOpKindChirho::RemIntChirho,
        "chr#" => PrimOpKindChirho::ChrChirho,
        "ord#" => PrimOpKindChirho::OrdChirho,
        "isDigit#" => PrimOpKindChirho::IsDigitChirho,
        "isAlpha#" => PrimOpKindChirho::IsAlphaChirho,
        "isAlphaNum#" => PrimOpKindChirho::IsAlphaNumChirho,
        "isUpper#" => PrimOpKindChirho::IsUpperChirho,
        "isLower#" => PrimOpKindChirho::IsLowerChirho,
        "isSpace#" => PrimOpKindChirho::IsSpaceChirho,
        "toLower#" => PrimOpKindChirho::ToLowerChirho,
        "toUpper#" => PrimOpKindChirho::ToUpperChirho,
        "digitToInt#" => PrimOpKindChirho::DigitToIntChirho,
        "intToDigit#" => PrimOpKindChirho::IntToDigitChirho,
        "==#" => PrimOpKindChirho::EqIntChirho,
        "/=#" => PrimOpKindChirho::NeIntChirho,
        "<#" => PrimOpKindChirho::LtIntChirho,
        "<=#" => PrimOpKindChirho::LeIntChirho,
        ">#" => PrimOpKindChirho::GtIntChirho,
        ">=#" => PrimOpKindChirho::GeIntChirho,
        "negate#" => PrimOpKindChirho::NegIntChirho,
        "putStrLn" | "putStrLn#" => PrimOpKindChirho::PutStrLnChirho,
        "putStr" | "putStr#" => PrimOpKindChirho::PutStrChirho,
        "putChar" | "putChar#" => PrimOpKindChirho::PutCharChirho,
        "return" | "pure" | "returnIO#" => PrimOpKindChirho::ReturnIOChirho,
        ">>=" | "bindIO#" => PrimOpKindChirho::BindIOChirho,
        ">>" | "thenIO#" => PrimOpKindChirho::ThenIOChirho,
        "getLine" | "getLine#" => PrimOpKindChirho::GetLineChirho,
        "getChar" | "getChar#" => PrimOpKindChirho::GetCharChirho,
        "getContents" | "getContents#" => PrimOpKindChirho::GetContentsChirho,
        "readFile" | "readFile#" => PrimOpKindChirho::ReadFileChirho,
        "writeFile" | "writeFile#" => PrimOpKindChirho::WriteFileChirho,
        "appendFile" | "appendFile#" => PrimOpKindChirho::AppendFileChirho,
        "showInt#" => PrimOpKindChirho::ShowIntChirho,
        "showBool#" => PrimOpKindChirho::ShowBoolChirho,
        "showChar#" => PrimOpKindChirho::ShowCharChirho,
        "not#" => PrimOpKindChirho::NotBoolChirho,
        "++#" => PrimOpKindChirho::AppendStrChirho,
        "eqStr#" => PrimOpKindChirho::EqStrChirho,
        "ltStr#" => PrimOpKindChirho::LtStrChirho,
        "compareStr#" => PrimOpKindChirho::CompareStrChirho,
        "eqFloat#" => PrimOpKindChirho::EqFloatChirho,
        "+.#" => PrimOpKindChirho::AddFloatChirho,
        "*.#" => PrimOpKindChirho::MulFloatChirho,
        "-.#" => PrimOpKindChirho::SubFloatChirho,
        "/.#" => PrimOpKindChirho::DivFloatChirho,
        "recip#" => PrimOpKindChirho::RecipFloatChirho,
        "negateFloat#" => PrimOpKindChirho::NegFloatChirho,
        "showFloat#" => PrimOpKindChirho::ShowFloatChirho,
        "lengthStr#" => PrimOpKindChirho::LengthStrChirho,
        "showStr#" => PrimOpKindChirho::ShowStrChirho,
        "enumFromTo#" => PrimOpKindChirho::EnumFromToChirho,
        "enumFrom#" => PrimOpKindChirho::EnumFromChirho,
        "enumFromThen#" => PrimOpKindChirho::EnumFromThenChirho,
        "enumFromThenTo#" => PrimOpKindChirho::EnumFromThenToChirho,
        "showList#" => PrimOpKindChirho::ShowListChirho,
        "readInt#" => PrimOpKindChirho::ReadIntChirho,
        "readFloat#" => PrimOpKindChirho::ReadFloatChirho,
        "readBool#" => PrimOpKindChirho::ReadBoolChirho,
        "wordsStr#" => PrimOpKindChirho::WordsStrChirho,
        "unwordsStr#" => PrimOpKindChirho::UnwordsStrChirho,
        "takeStr#" => PrimOpKindChirho::TakeStrChirho,
        "dropStr#" => PrimOpKindChirho::DropStrChirho,
        "concatStr#" => PrimOpKindChirho::ConcatStrChirho,
        "intercalateStr#" => PrimOpKindChirho::IntercalateStrChirho,
        "fromIntegral#" => PrimOpKindChirho::FromIntegralChirho,
        "ceiling#" => PrimOpKindChirho::CeilingChirho,
        "floor#" => PrimOpKindChirho::FloorChirho,
        "round#" => PrimOpKindChirho::RoundChirho,
        "truncate#" => PrimOpKindChirho::TruncateChirho,
        "compare#" => PrimOpKindChirho::CompareIntChirho,
        "compareChar#" => PrimOpKindChirho::CompareCharChirho,
        "compareFloat#" => PrimOpKindChirho::CompareFloatChirho,
        "<.#" => PrimOpKindChirho::LtFloatChirho,
        ">.#" => PrimOpKindChirho::GtFloatChirho,
        // Floating math primops
        "sin#" => PrimOpKindChirho::SinFloatChirho,
        "cos#" => PrimOpKindChirho::CosFloatChirho,
        "tan#" => PrimOpKindChirho::TanFloatChirho,
        "asin#" => PrimOpKindChirho::AsinFloatChirho,
        "acos#" => PrimOpKindChirho::AcosFloatChirho,
        "atan#" => PrimOpKindChirho::AtanFloatChirho,
        "exp#" => PrimOpKindChirho::ExpFloatChirho,
        "log#" => PrimOpKindChirho::LogFloatChirho,
        "sqrt#" => PrimOpKindChirho::SqrtFloatChirho,
        "pi#" => PrimOpKindChirho::PiFloatChirho,
        "^#" => PrimOpKindChirho::PowIntChirho,
        "**#" => PrimOpKindChirho::PowFloatChirho,
        "id#" => PrimOpKindChirho::IdChirho,
        "error" => PrimOpKindChirho::ErrorChirho,
        "undefined" => PrimOpKindChirho::UndefinedChirho,
        "seq" | "deepseq" => PrimOpKindChirho::SeqChirho,
        "evaluate" => PrimOpKindChirho::EvaluateChirho,
        "force" | "force#" => PrimOpKindChirho::ForceChirho,
        "showMaybe#" => PrimOpKindChirho::ShowMaybeChirho,
        "showTuple2#" => PrimOpKindChirho::ShowTuple2Chirho,
        "showEither#" => PrimOpKindChirho::ShowEitherChirho,
        "showOrdering#" => PrimOpKindChirho::ShowOrderingChirho,
        "interact" => PrimOpKindChirho::InteractChirho,
        "print" | "print#" => PrimOpKindChirho::PrintChirho,
        "lines#" => PrimOpKindChirho::LinesChirho,
        "unlines#" => PrimOpKindChirho::UnlinesChirho,
        // IORef primops
        "newIORef" | "newIORef#" => PrimOpKindChirho::NewIORefChirho,
        "readIORef" | "readIORef#" => PrimOpKindChirho::ReadIORefChirho,
        "writeIORef" | "writeIORef#" => PrimOpKindChirho::WriteIORefChirho,
        "modifyIORef" | "modifyIORef#" => PrimOpKindChirho::ModifyIORefChirho,
        // ST monad primops
        "newSTRef" | "newSTRef#" => PrimOpKindChirho::NewSTRefChirho,
        "readSTRef" | "readSTRef#" => PrimOpKindChirho::ReadSTRefChirho,
        "writeSTRef" | "writeSTRef#" => PrimOpKindChirho::WriteSTRefChirho,
        "modifySTRef" | "modifySTRef#" => PrimOpKindChirho::ModifySTRefChirho,
        "runST" | "runST#" => PrimOpKindChirho::RunSTChirho,
        // STM primops
        "newTVar" | "newTVar#" | "newTVarIO" | "newTVarIO#" => PrimOpKindChirho::NewTVarChirho,
        "readTVar" | "readTVar#" | "readTVarIO" | "readTVarIO#" => PrimOpKindChirho::ReadTVarChirho,
        "writeTVar" | "writeTVar#" => PrimOpKindChirho::WriteTVarChirho,
        "atomically" | "atomically#" => PrimOpKindChirho::AtomicallyChirho,
        "retry" | "retry#" => PrimOpKindChirho::RetryChirho,
        "orElse" | "orElse#" => PrimOpKindChirho::OrElseChirho,
        // Exception handling primops
        "catch" | "catch#" => PrimOpKindChirho::CatchChirho,
        "throw" | "throw#" | "throwIO" | "throwIO#" => PrimOpKindChirho::ThrowChirho,
        "try" | "try#" => PrimOpKindChirho::TryChirho,
        "bracket" | "bracket#" => PrimOpKindChirho::BracketChirho,
        "finally" | "finally#" => PrimOpKindChirho::FinallyChirho,
        // Data.Map primops
        "mapEmpty#" | "mapEmpty" => PrimOpKindChirho::MapEmptyChirho,
        "mapSingleton#" | "mapSingleton" => PrimOpKindChirho::MapSingletonChirho,
        "mapInsert#" | "mapInsert" => PrimOpKindChirho::MapInsertChirho,
        "mapLookup#" | "mapLookup" => PrimOpKindChirho::MapLookupChirho,
        "mapDelete#" | "mapDelete" => PrimOpKindChirho::MapDeleteChirho,
        "mapMember#" | "mapMember" => PrimOpKindChirho::MapMemberChirho,
        "mapSize#" | "mapSize" => PrimOpKindChirho::MapSizeChirho,
        "mapFromList#" | "mapFromList" => PrimOpKindChirho::MapFromListChirho,
        "mapToList#" | "mapToList" => PrimOpKindChirho::MapToListChirho,
        "mapKeys#" | "mapKeys" => PrimOpKindChirho::MapKeysChirho,
        "mapElems#" | "mapElems" => PrimOpKindChirho::MapElemsChirho,
        "mapNull#" | "mapNull" => PrimOpKindChirho::MapNullChirho,
        "mapMap#" | "mapMap" => PrimOpKindChirho::MapMapChirho,
        "mapFoldlWithKey#" | "mapFoldlWithKey" => PrimOpKindChirho::MapFoldlWithKeyChirho,
        "mapFoldrWithKey#" | "mapFoldrWithKey" => PrimOpKindChirho::MapFoldrWithKeyChirho,
        "mapUnion#" | "mapUnion" => PrimOpKindChirho::MapUnionChirho,
        "mapDifference#" | "mapDifference" => PrimOpKindChirho::MapDifferenceChirho,
        "mapIntersection#" | "mapIntersection" => PrimOpKindChirho::MapIntersectionChirho,
        "mapIntersectionWith#" | "mapIntersectionWith" => {
            PrimOpKindChirho::MapIntersectionWithChirho
        }
        "mapInsertWith#" | "mapInsertWith" => PrimOpKindChirho::MapInsertWithChirho,
        "mapFindWithDefault#" | "mapFindWithDefault" => PrimOpKindChirho::MapFindWithDefaultChirho,
        "mapAdjust#" | "mapAdjust" => PrimOpKindChirho::MapAdjustChirho,
        "mapUnionWith#" | "mapUnionWith" => PrimOpKindChirho::MapUnionWithChirho,
        "mapFilter#" | "mapFilter" => PrimOpKindChirho::MapFilterChirho,
        "mapFilterWithKey#" | "mapFilterWithKey" => PrimOpKindChirho::MapFilterWithKeyChirho,
        // Data.Set primops
        "setEmpty#" | "setEmpty" => PrimOpKindChirho::SetEmptyChirho,
        "setSingleton#" | "setSingleton" => PrimOpKindChirho::SetSingletonChirho,
        "setInsert#" | "setInsert" => PrimOpKindChirho::SetInsertChirho,
        "setMember#" | "setMember" => PrimOpKindChirho::SetMemberChirho,
        "setDelete#" | "setDelete" => PrimOpKindChirho::SetDeleteChirho,
        "setSize#" | "setSize" => PrimOpKindChirho::SetSizeChirho,
        "setFromList#" | "setFromList" => PrimOpKindChirho::SetFromListChirho,
        "setToList#" | "setToList" => PrimOpKindChirho::SetToListChirho,
        "setUnion#" | "setUnion" => PrimOpKindChirho::SetUnionChirho,
        "setIntersection#" | "setIntersection" => PrimOpKindChirho::SetIntersectionChirho,
        "setDifference#" | "setDifference" => PrimOpKindChirho::SetDifferenceChirho,
        "setNull#" | "setNull" => PrimOpKindChirho::SetNullChirho,
        "setMap#" | "setMap" => PrimOpKindChirho::SetMapChirho,
        "setFilter#" | "setFilter" => PrimOpKindChirho::SetFilterChirho,
        "setFoldr#" | "setFoldr" | "setFold#" | "setFold" => PrimOpKindChirho::SetFoldrChirho,
        _ => return None,
    })
}
