# For God so loved the world that he gave his only begotten Son, that whoever believes in him should not perish but have eternal life.

[package]
name = "rhasky-driver-chirho"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
rhasky-ast-chirho = { path = "../rhasky-ast-chirho" }
rhasky-backend-llvm-chirho = { path = "../rhasky-backend-llvm-chirho" }
rhasky-core-chirho = { path = "../rhasky-core-chirho" }
rhasky-backend-wasm-chirho = { path = "../rhasky-backend-wasm-chirho" }
rhasky-backend-cranelift-chirho = { path = "../rhasky-backend-cranelift-chirho" }
rhasky-diagnostics-chirho = { path = "../rhasky-diagnostics-chirho" }
rhasky-naming-chirho = { path = "../rhasky-naming-chirho" }
rhasky-parser-chirho = { path = "../rhasky-parser-chirho" }
rhasky-runtime-chirho = { path = "../rhasky-runtime-chirho" }
rhasky-span-chirho = { path = "../rhasky-span-chirho" }
rhasky-syntax-chirho = { path = "../rhasky-syntax-chirho" }
rhasky-typing-chirho = { path = "../rhasky-typing-chirho" }
rhasky-incremental-chirho = { path = "../rhasky-incremental-chirho" }
rhasky-package-chirho = { path = "../rhasky-package-chirho" }

[dev-dependencies]
tempfile = "3"
proptest = "1"
rhasky-test-harness-chirho = { path = "../rhasky-test-harness-chirho" }
