# For God so loved the world that he gave his only begotten Son, that whoever believes in him should not perish but have eternal life.

[package]
name = "haskeluya-cli-chirho"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "haskeluya-cli-chirho"
path = "src/main.rs"

[dependencies]
haskeluya-ast-chirho = { path = "../haskeluya-ast-chirho" }
haskeluya-backend-cranelift-chirho = { path = "../haskeluya-backend-cranelift-chirho" }
haskeluya-backend-llvm-chirho = { path = "../haskeluya-backend-llvm-chirho" }
haskeluya-backend-wasm-chirho = { path = "../haskeluya-backend-wasm-chirho" }
haskeluya-core-chirho = { path = "../haskeluya-core-chirho" }
haskeluya-naming-chirho = { path = "../haskeluya-naming-chirho" }
haskeluya-package-chirho = { path = "../haskeluya-package-chirho" }
haskeluya-driver-chirho = { path = "../haskeluya-driver-chirho" }
haskeluya-runtime-chirho = { path = "../haskeluya-runtime-chirho" }
haskeluya-span-chirho = { path = "../haskeluya-span-chirho" }
haskeluya-syntax-chirho = { path = "../haskeluya-syntax-chirho" }
haskeluya-typing-chirho = { path = "../haskeluya-typing-chirho" }

